### ISSUE TITLE
Bigger size for input fields

### ISSUE THREAD

**Issue by sebix** [MGVmedia/regexpad#15]
I regex codes I usually test are some hundred characters long, and I need two or three times the lines which are displayed by default. Currently it is not possible to expand the size of the text areas on demand or let it automatically resize.

**Comment by SebastianVomMeer** [comment]
Hello Sebix,

thanks for using Regexpad. I reenabled resizing of textareas, which should work in Chrome and Firefox at least. If something looks wrong try to reload the page explicitly using F5 (our assets are not timestamped yet).

**Comment by sebix** [comment]
Oh, that was fast! Works as expected, many thanks.
